name: Staging Build & Push - Automatic

on:
  push:
    branches:
      - "main"
    paths:
      - Dockerfile
      - pyproject.toml
      - poetry.lock
      - .github/workflows/staging-build.yml

jobs:
  build:
    uses: cloudsteak/cm-workflows/.github/workflows/staging-build-push.yml@1.3.0
    with:
      image_name: ${{ github.event.repository.name }}
